### ISSUE TITLE
Connect Sanity as CMS

### ISSUE THREAD

**Issue by tossivahva** [MorganKryze/Portfolio#1]
Hi Morgan! 

This project is very elegant visually + animation, love it! I would like to use it as a boilerplate for my photography project. What I need is to integrate CMS system to manage new photo and photo albums/group upload. Is it good idea to connect this project to Sanity (I googled that it is very popular for Astro).

What is your thoughs or suggestions as a developer?

**Comment by MorganKryze** [comment]
Hi tossivahva!

Thank you for the feedback, I appreciate it!
To be completely honest, a CMS would have been a better idea than my actual configuration. I first thought to implement a Minio instance to the project but seemed too much. On the other hand I hadn't heard of Sanity since now and after giving it a look it seems to be a great alternative (I feel that implementing it would be my goal for my next web-project).

However, depending on your configuration, you may consider using a service as Vercel, Fly.io or personal host though, github pages will have its limitations.

**Comment by tossivahva** [comment]
@MorganKryze I also found [Strapi](https://github.com/strapi/strapi) - a headless CMS most loved by community as well as this is an open source solution, give a try to that one. For now it feels very simple and suitable for this kind of tasks. Thank you for your reply btw!
